### ISSUE TITLE
Fetch Categories by name not working

### ISSUE THREAD

**Issue by mohankumar27** [catoverse/yellowjobs-backend-service#10]
While testing the API in Swagger, fetching Catergories by passing name param throws error. Refer below image
![image](https://user-images.githubusercontent.com/25298468/129452739-2e78e60f-1b91-412a-946a-45382cc4ae69.png)

Issue is found on *controllers/category.js* where **categoriesKeywords** is not defined
![image](https://user-images.githubusercontent.com/25298468/129452786-4b18f9ae-f12d-4abf-96ee-f6e1e1dd413c.png)

**Comment by mohankumar27** [comment]
@anshulagx  can i work on this issue ?

**Comment by anshulagx** [comment]
Yes please. That would be great.
Fork and then create a pull request. I will assign you.

**Comment by mohankumar27** [comment]
Will raise pull request by today

**Comment by mohankumar27** [comment]
@anshulagx  kindly review #11

**Comment by anshulagx** [comment]
Merged! Thanks
