### ISSUE TITLE
arrange the roles list in alphabetical order

### ISSUE THREAD

**Issue by anshulagx** [catoverse/yellowjobs-backend-service#6]
When the user clicks on a category (say Tech) , he is greeted with several options to choose from. Arrange those options in alphabetical order.

**Comment by anshulagx** [comment]
Edit this file
https://github.com/catoverse/yellowjobs-backend-service/blob/main/data/roles.json

**Comment by meamitacharya** [comment]
Could u assign this to me??

**Comment by anshulagx** [comment]
Done!
Create a new feature branch and submit the pull request to the staging branch. Feel free to ask for help.

**Comment by meamitacharya** [comment]
I couldn't push from my local repo. (unable to access the requested URL).
Will you give access to your repo??
@anshulagx

**Comment by anshulagx** [comment]
Hey,
Why don't you try this flow
fork -> clone -> switch branch -> make changes -> commit -> push to your fork -> create a PR to this repo.

**Comment by meamitacharya** [comment]
Done! 
Check it out.

**Comment by anshulagx** [comment]
Merged the updated tech list
